##########################################################################
name: Build CI (x86_64)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - uses: actions/checkout@v2
##########################################################################
      - name: Install Git
        run: |
          sudo pacman -Syyyu git --noconfirm
          
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v4.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Build Ice Linux For x86_64
        run: |
          chmod +x build_x86_64.sh
          sudo bash build_x86_64.sh
      
      - name: Upload Ice Linux x86_64 Iso
        uses: actions/upload-artifact@v2
        with:
            name: IceLinux-x86_64
            path: icelinux_x86_64/out/*
            if-no-files-found: error
