name: BUILD CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Starting Self Hosted Runner
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Build IceLinux 
        run: |
          chmod +x build.sh
          sudo ./build.sh -v 
