############################################################################
name: BUILD CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: archlinux
#############################################################################
    steps:
      - uses: actions/checkout@v2
      - name: Build IceLinux 
        run: | 
          sudo chmod +x build.sh
          sudo ./build.sh -N icelinux -L "AI$(date +%Y%m)" -P "IceLinux <https://github.com/NekoIceCream/IceLinux>" -v
##############################################################################
#- name: Upload a Build Artifact
#  uses: actions/upload-artifact@v2.2.4
#  with:
#    name: 
#    path:
    
#Available Options:
#  warn: Output a warning but do not fail the action
#  error: Fail the action with an error message
#  ignore: Do not output any warnings or errors, the action does not fail

#    if-no-files-found:
#    retention-days:
##############################################################################