#####################################################
name: Build CI
on:
  pull_request:
    branches: [ main ]
  paths-ignore:
    - '*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ArchLinux

    steps:
      - uses: actions/checkout@v2
      - name: Build IceLinux 
        run: |
          chmod +x build.sh
          sudo ./build.sh
########################################################