#####################################################
name: Build CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ArchLinux

    steps:
      - uses: actions/checkout@v2
      - name: Build IceLinux For x86_64
        run: |
          chmod +x build_86_64.sh
          sudo ./build_x86_64.sh
########################################################
